Fixes a crash
```
19:46:13.087  E  Error was captured in composition. (Fix with AI)
                 java.lang.IllegalStateException: No CircuitSaver provided. Wrap this content in CircuitCompositionLocals or ProvideCircuitSaver, or pass a CircuitSaver directly to the remember API.
                 	at com.slack.circuit.runtime.screen.CircuitSaverKt.LocalCircuitSaver$lambda$0(CircuitSaver.kt:186)
                 	at com.slack.circuit.runtime.screen.CircuitSaverKt$$ExternalSyntheticLambda1.invoke(D8$$SyntheticClass:0)
                 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:86)
                 	at androidx.compose.runtime.LazyValueHolder.getCurrent(ValueHolders.kt:46)
                 	at androidx.compose.runtime.LazyValueHolder.readValue(ValueHolders.kt:48)
                 	at androidx.compose.runtime.CompositionLocalMapKt.read(CompositionLocalMap.kt:88)
                 	at androidx.compose.runtime.GapComposer.consume(GapComposer.kt:1235)
                 	at com.slack.circuit.foundation.navstack.SaveableNavStackKt.rememberSaveableNavStack(SaveableNavStack.kt:436)
                 	at dev.hossain.syntaxhighlight.MainActivity.onCreate$lambda$0$0(MainActivity.kt:61)
                 	at dev.hossain.syntaxhighlight.MainActivity.$r8$lambda$OIy4X7-A8lbQ1eBmddGammCP3Fk(MainActivity.kt:0)
                 	at dev.hossain.syntaxhighlight.MainActivity$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass:0)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:122)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:52)
                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:428)
                 	at androidx.compose.material3.TextKt.ProvideTextStyle(Text.kt:462)
                 	at androidx.compose.material3.MaterialThemeKt$MaterialTheme$2.invoke(MaterialTheme.kt:107)
                 	at androidx.compose.material3.MaterialThemeKt$MaterialTheme$2.invoke(MaterialTheme.kt:106)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:122)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:52)
                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:408)
                 	at androidx.compose.material3.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:99)
                 	at androidx.compose.material3.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:60)
                 	at dev.hossain.syntaxhighlight.ui.theme.ThemeKt.SyntaxHighlightAppTheme(Theme.kt:50)
                 	at dev.hossain.syntaxhighlight.MainActivity.onCreate$lambda$0(MainActivity.kt:59)
                 	at dev.hossain.syntaxhighlight.MainActivity$$ExternalSyntheticLambda2.invoke(D8$$SyntheticClass:0)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:122)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:52)
                 	at androidx.compose.ui.platform.ComposeView.Content(ComposeView.android.kt:615)
                 	at androidx.compose.ui.platform.AbstractComposeView.ensureCompositionCreated$lambda$0$0(ComposeView.android.kt:335)
                 	at androidx.compose.ui.platform.AbstractComposeView.$r8$lambda$haJlVCuyZDQPMe6uz0Clg0Uri0w(ComposeView.android.kt:0)
                 	at androidx.compose.ui.platform.AbstractComposeView$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass:0)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:122)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:52)
                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:408)
                 	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:255)
                 	at androidx.compose.ui.platform.ComposeViewContext.ProvideCompositionLocals$lambda$4(ComposeViewContext.android.kt:518)
                 	at androidx.compose.ui.platform.ComposeViewContext$$ExternalSyntheticLambda4.invoke(D8$$SyntheticClass:0)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:122)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:52)
                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:408)
19:46:13.088  E  	at androidx.compose.ui.platform.ComposeViewContext.ProvideCompositionLocals$ui(ComposeViewContext.android.kt:490) (Fix with AI)
                 	at androidx.compose.ui.platform.WrappedComposition.setContent$lambda$0$1(Wrapper.android.kt:126)
                 	at androidx.compose.ui.platform.WrappedComposition.$r8$lambda$6M750dKfgrqZayQXx8RTdC0WEQA(Wrapper.android.kt:0)
                 	at androidx.compose.ui.platform.WrappedComposition$$ExternalSyntheticLambda1.invoke(D8$$SyntheticClass:0)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:122)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:52)
                 	at androidx.compose.runtime.internal.Expect_jvmKt.invokeComposable(Expect.jvmAndAndroid.kt:26)
                 	at androidx.compose.runtime.GapComposer.doCompose-aFTiNEg(GapComposer.kt:2643)
                 	at androidx.compose.runtime.GapComposer.composeContent--ZbOJvo$runtime(GapComposer.kt:2545)
                 	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:905)
                 	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:1178)
                 	at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:735)
                 	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:702)
                 	at androidx.compose.ui.platform.WrappedComposition.setContent$lambda$0(Wrapper.android.kt:123)
                 	at androidx.compose.ui.platform.WrappedComposition$$ExternalSyntheticLambda2.invoke(D8$$SyntheticClass:0)
                 	at androidx.compose.ui.platform.AndroidComposeView.setOnReadyForComposition(AndroidComposeView.android.kt:2324)
                 	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:105)
                 	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:155)
                 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:394)
                 	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:249)
                 	at androidx.compose.ui.platform.WrappedComposition.setContent$lambda$0(Wrapper.android.kt:120)
                 	at androidx.compose.ui.platform.WrappedComposition$$ExternalSyntheticLambda2.invoke(D8$$SyntheticClass:0)
                 	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:2395)
                 	at android.view.View.dispatchAttachedToWindow(View.java:23294)
                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3517)
                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3524)
                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3524)
                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3524)
                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3524)
                 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3667)
                 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3127)
                 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10807)
                 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1630)
                 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1639)
                 	at android.view.Choreographer.doCallbacks(Choreographer.java:1235)
                 	at android.view.Choreographer.doFrame(Choreographer.java:1164)
                 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1613)
                 	at android.os.Handler.handleCallback(Handler.java:1070)
                 	at android.os.Handler.dispatchMessage(Handler.java:125)
                 	at android.os.Looper.dispatchMessage(Looper.java:333)
                 	at android.os.Looper.loopOnce(Looper.java:263)
                 	at android.os.Looper.loop(Looper.java:367)
                 	at android.app.ActivityThread.main(ActivityThread.java:9287)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:566)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:929)
```